services:
  - type: web
    name: stats-engine-matchstats
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MATCHSTATS_URL
        value: https://matchstats.us.ffesports.com/
